---
#
# This role should be run with sudo=yes sudo_user={{ install_user }}.
#

#
# CAS
#

- set_fact:
    install_archive: "V46393-01.zip"
    install_executable: "OCcas11.1.0-Linux64.sh"
    tmpdir: /tmp

- name: temporary directory for install
  register: mktemp
  command: mktemp -d

- name: download installation archive
  get_url:
  args:
    url: "{{ install_archive_url }}"
    dest: "{{ playbook_dir }}/{{ install_archive }}"
  when: install_archive_url is defined

- name: expand CAS archive
  unarchive: 
    src="{{ install_archive }}"
    dest="{{ mktemp.stdout }}"
    creates="{{ mktemp.stdout }}/{{ install_executable }}"

- name: ensure CAS install file is executable
  file:
  args:
    path: "{{ mktemp.stdout}}/{{ install_executable }}"
    mode: 0744

- name: create silent install file for cas 
  template:
  args:
    src: "cas_silent.j2"
    dest: "{{ mktemp.stdout }}/cas_silent.txt"

- name: install cas
  command: "{{ mktemp.stdout }}/{{ install_executable }} --silent --target {{ install_root }} < '{{ mktemp.stdout }}/cas_silent.txt' 2>&1 > /tmp/cas_install.log creates={{ install_root }}/endeca/CAS"
  environment:
    ENDECA_TOOLS_ROOT: "{{ install_root }}/endeca/ToolsAndFrameworks/11.1.0"
    ENDECA_TOOLS_CONF: "{{ install_root }}/endeca/ToolsAndFrameworks/11.1.0/server/workspace"

- include: init.yml tags=configure_service

- name: clean up temporary directory
  file: 
    state=absent 
    path="{{ mktemp.stdout }}"

